clear all
X=0:0.1:10;
X=X';
d=sin(X);
b = TreeBagger(50,X,d,...
           'minleaf',3,...
           'Method','regression',...
           'oobpred','on', ...
           'OOBVarImp', 'on', ...
           'NVarToSample',3)
Xtest=0:0.126:10;
Xtest=Xtest';
y=predict(b,Xtest)
figure, plot(X,d,'r',Xtest,y,'b') 
grid, xlabel('x'), ylabel('f(x)')
